title = "Hugo Serif Theme"
baseURL = "www.example.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

[params.logo]
standard = "images/logo.svg"
mobile = "images/logo-mobile.svg"
alt = "Serif - A Hugo Business Theme"

[params.homepage_meta_tags]
meta_description = "One mobile app to create an online shop and take orders over the internet from nearby customers & manage all your in shop operations with Raseedbook app"
meta_og_url = "https://hugo-serif.netlify.com"
meta_twitter_creator = "@zerostaticio"
meta_og_type = "website"
meta_og_title = "Mobiles App for Shopkeepers "
meta_twitter_site = "@zerostaticio"
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_description = "Run your business from your phone"
meta_twitter_card = "summary"

[menu]

[[menu.main]]
name = "Digitising Cash Memo and Increasing Sales "
url = "/Home/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2