title = "RaseedBook"
baseURL = "www.example.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

[params.logo]
standard = "/images/icon.png"
mobile = "/images/icon.png"
alt = "RaseedBook Logo"

[params.homepage_meta_tags]
meta_description = "One mobile app to create an online shop and take orders over the internet from nearby customers & manage all your in shop operations with Raseedbook app"
meta_og_url = ""
meta_twitter_creator = ""
meta_og_type = "website"
meta_og_title = "Mobiles App for Shopkeepers "
meta_twitter_site = ""
meta_og_image = ""
meta_og_description = "Run your business from your phone"
meta_twitter_card = ""

[menu]
footer = []

[[menu.main]]
name = "Services"
url = "/Services/"
weight = 2

[[menu.main]]
name = "Team"
url = "/team/"
weight = 3

[[menu.main]]
identifier = "Home"
url = "/"
name = "Home"
weight = 1